package com.aicoding.platform.audit.domain;

public enum AuditActionType {
    AUTH_LOGIN,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    MEMBER_INVITE,
    REPOSITORY_BIND,
    TASK_CREATE,
    TASK_EXECUTE,
    TASK_CANCEL,
    AGENT_CREATE,
    CHAT_SEND,
    RAG_DOCUMENT_UPLOAD,
    RAG_SEARCH,
    MODEL_CALL,
    SYSTEM_OPERATION,
    GITHUB_OAUTH_START,
    GITHUB_OAUTH_CALLBACK,
    GITHUB_REPOSITORY_SYNC,
    GITHUB_PR_FETCH,
    PR_REVIEW_START,
    PR_REVIEW_COMPLETE,
    PR_REVIEW_FAILED,
    MULTI_AGENT_APPROVE,
    MULTI_AGENT_REJECT,
    TOOL_PARAMETER_UPDATE
}
