CREATE TABLE IF NOT EXISTS tool_sandbox_execution (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    run_id BIGINT NULL,
    phase_id BIGINT NULL,
    step_id BIGINT NULL,
    agent_id BIGINT NULL,
    tool_name VARCHAR(64) NOT NULL,
    tool_type VARCHAR(32) NOT NULL,
    execution_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_payload JSON NULL,
    output_payload JSON NULL,
    summary TEXT NULL,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    duration_ms BIGINT DEFAULT 0,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    INDEX idx_tool_sandbox_project_time(project_id, create_time),
    INDEX idx_tool_sandbox_task(task_id),
    INDEX idx_tool_sandbox_run(run_id),
    INDEX idx_tool_sandbox_step(step_id),
    INDEX idx_tool_sandbox_agent(agent_id),
    INDEX idx_tool_sandbox_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安全工具沙箱执行记录';
