CREATE TABLE IF NOT EXISTS tool_execution_job (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    run_id BIGINT NULL,
    step_id BIGINT NULL,
    tool_execution_id BIGINT NOT NULL,
    tool_key VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 2,
    request_payload JSON NULL,
    result_payload JSON NULL,
    last_error TEXT NULL,
    locked_by VARCHAR(128) NULL,
    locked_at DATETIME NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    duration_ms BIGINT DEFAULT 0,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    INDEX idx_tool_job_project_time(project_id, create_time),
    INDEX idx_tool_job_task(task_id),
    INDEX idx_tool_job_run(run_id),
    INDEX idx_tool_job_step(step_id),
    INDEX idx_tool_job_execution(tool_execution_id),
    INDEX idx_tool_job_status(status),
    INDEX idx_tool_job_tool(tool_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具执行队列作业表';
