-- V26: Seed 4 Read-only Repository Tools

-- 910101: READ_REPOSITORY_TREE
INSERT INTO tool_catalog (id, tool_key, name, description, tool_type, risk_level, execution_mode, enabled, built_in, policy_json, parameter_schema_json, create_time, update_time) VALUES
(910101, 'READ_REPOSITORY_TREE', '读取仓库文件树', '只读扫描项目仓库文件结构，返回目录树和文件列表。不读取文件内容，不执行 Git 写操作。', 'READ_ONLY', 'LOW', 'MOCK_EXECUTE', 1, 1, '{"allowedStepTypes":["ARCHITECTURE_ANALYSIS","FINAL_SUMMARY","CODE_REVIEW"],"readOnly":true,"allowShell":false,"allowGitWrite":false,"allowFileWrite":false}', '{"fields":[{"key":"branch","label":"分支","type":"text","required":false,"defaultValue":"","maxLength":128},{"key":"pathPrefix","label":"路径前缀","type":"text","required":false,"defaultValue":"","maxLength":256},{"key":"maxFiles","label":"最大文件数","type":"number","required":true,"defaultValue":50,"min":1,"max":200}]}', NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), tool_type=VALUES(tool_type), risk_level=VALUES(risk_level), execution_mode=VALUES(execution_mode), enabled=VALUES(enabled), built_in=VALUES(built_in), policy_json=VALUES(policy_json), parameter_schema_json=VALUES(parameter_schema_json), update_time=NOW();

-- 910102: READ_FILE_SNIPPET
INSERT INTO tool_catalog (id, tool_key, name, description, tool_type, risk_level, execution_mode, enabled, built_in, policy_json, parameter_schema_json, create_time, update_time) VALUES
(910102, 'READ_FILE_SNIPPET', '读取文件片段', '只读读取项目仓库中指定文件的指定行范围内容。不读取敏感文件，不执行 Git 写操作。', 'READ_ONLY', 'MEDIUM', 'MOCK_EXECUTE', 1, 1, '{"allowedStepTypes":["ARCHITECTURE_ANALYSIS","BACKEND_IMPLEMENTATION_PLAN","FRONTEND_IMPLEMENTATION_PLAN","CODE_REVIEW"],"readOnly":true,"allowShell":false,"allowGitWrite":false,"allowFileWrite":false}', '{"fields":[{"key":"branch","label":"分支","type":"text","required":false,"defaultValue":"","maxLength":128},{"key":"filePath","label":"文件路径","type":"text","required":true,"defaultValue":"","maxLength":512},{"key":"startLine","label":"起始行","type":"number","required":false,"defaultValue":1,"min":1,"max":100000},{"key":"maxLines","label":"最大行数","type":"number","required":true,"defaultValue":80,"min":1,"max":300}]}', NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), tool_type=VALUES(tool_type), risk_level=VALUES(risk_level), execution_mode=VALUES(execution_mode), enabled=VALUES(enabled), built_in=VALUES(built_in), policy_json=VALUES(policy_json), parameter_schema_json=VALUES(parameter_schema_json), update_time=NOW();

-- 910103: READ_DIFF_SUMMARY
INSERT INTO tool_catalog (id, tool_key, name, description, tool_type, risk_level, execution_mode, enabled, built_in, policy_json, parameter_schema_json, create_time, update_time) VALUES
(910103, 'READ_DIFF_SUMMARY', '读取 Diff 摘要', '只读读取指定基准分支与当前分支的差异摘要。不执行 git diff shell，不修改任何文件。', 'READ_ONLY', 'MEDIUM', 'MOCK_EXECUTE', 1, 1, '{"allowedStepTypes":["CODE_REVIEW","BACKEND_IMPLEMENTATION_PLAN","FRONTEND_IMPLEMENTATION_PLAN","FINAL_SUMMARY"],"readOnly":true,"allowShell":false,"allowGitWrite":false,"allowFileWrite":false}', '{"fields":[{"key":"branch","label":"分支","type":"text","required":false,"defaultValue":"","maxLength":128},{"key":"baseBranch","label":"基准分支","type":"text","required":false,"defaultValue":"main","maxLength":128},{"key":"maxFiles","label":"最大文件数","type":"number","required":true,"defaultValue":30,"min":1,"max":100}]}', NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), tool_type=VALUES(tool_type), risk_level=VALUES(risk_level), execution_mode=VALUES(execution_mode), enabled=VALUES(enabled), built_in=VALUES(built_in), policy_json=VALUES(policy_json), parameter_schema_json=VALUES(parameter_schema_json), update_time=NOW();

-- 910104: READ_BRANCH_INFO
INSERT INTO tool_catalog (id, tool_key, name, description, tool_type, risk_level, execution_mode, enabled, built_in, policy_json, parameter_schema_json, create_time, update_time) VALUES
(910104, 'READ_BRANCH_INFO', '读取分支信息', '只读查询项目仓库分支列表和基本信息。不执行 checkout，不执行 pull，不修改任何文件。', 'READ_ONLY', 'LOW', 'MOCK_EXECUTE', 1, 1, '{"allowedStepTypes":["CODE_REVIEW","ARCHITECTURE_ANALYSIS","FINAL_SUMMARY"],"readOnly":true,"allowShell":false,"allowGitWrite":false,"allowFileWrite":false}', '{"fields":[{"key":"includeRemote","label":"包含远程分支","type":"boolean","required":false,"defaultValue":true},{"key":"maxBranches","label":"最大分支数","type":"number","required":true,"defaultValue":30,"min":1,"max":100}]}', NOW(), NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), tool_type=VALUES(tool_type), risk_level=VALUES(risk_level), execution_mode=VALUES(execution_mode), enabled=VALUES(enabled), built_in=VALUES(built_in), policy_json=VALUES(policy_json), parameter_schema_json=VALUES(parameter_schema_json), update_time=NOW();
