CREATE TABLE tool_operator_review (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    run_id BIGINT NULL,
    tool_execution_id BIGINT NULL,
    tool_job_id BIGINT NULL,
    review_target_type VARCHAR(32) NOT NULL,
    review_target_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    resolution TEXT NULL,
    assignee_id BIGINT NULL,
    created_by BIGINT NOT NULL,
    resolved_by BIGINT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    resolved_at DATETIME NULL,
    KEY idx_tool_operator_review_project_time (project_id, create_time),
    KEY idx_tool_operator_review_target (review_target_type, review_target_id),
    KEY idx_tool_operator_review_execution (tool_execution_id),
    KEY idx_tool_operator_review_job (tool_job_id),
    KEY idx_tool_operator_review_status (status),
    KEY idx_tool_operator_review_assignee (assignee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具执行操作员审查记录表';
