CREATE TABLE tool_incident (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    run_id BIGINT NULL,
    tool_execution_id BIGINT NULL,
    tool_job_id BIGINT NULL,
    operator_review_id BIGINT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    severity VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    resolution TEXT NULL,
    assignee_id BIGINT NULL,
    created_by BIGINT NULL,
    acknowledged_by BIGINT NULL,
    resolved_by BIGINT NULL,
    first_seen_at DATETIME NOT NULL,
    last_seen_at DATETIME NOT NULL,
    acknowledged_at DATETIME NULL,
    resolved_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_tool_incident_project_time(project_id, create_time),
    KEY idx_tool_incident_status(status),
    KEY idx_tool_incident_severity(severity),
    KEY idx_tool_incident_execution(tool_execution_id),
    KEY idx_tool_incident_job(tool_job_id),
    KEY idx_tool_incident_review(operator_review_id),
    KEY idx_tool_incident_source(source_type, source_id),
    KEY idx_tool_incident_assignee(assignee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具执行事件表';

CREATE TABLE tool_alert_rule (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NULL,
    name VARCHAR(128) NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    source_type VARCHAR(32) NOT NULL,
    min_severity VARCHAR(32) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    route_target VARCHAR(255) NULL,
    config_json JSON NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_tool_alert_rule_project(project_id),
    KEY idx_tool_alert_rule_enabled(enabled),
    KEY idx_tool_alert_rule_source(source_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具告警规则表';

CREATE TABLE tool_alert_delivery (
    id BIGINT PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    rule_id BIGINT NULL,
    channel VARCHAR(32) NOT NULL,
    route_target VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL,
    payload TEXT NULL,
    error_message TEXT NULL,
    delivered_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_tool_alert_delivery_incident(incident_id),
    KEY idx_tool_alert_delivery_project_time(project_id, create_time),
    KEY idx_tool_alert_delivery_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工具告警投递记录表';
