CREATE TABLE tool_incident_retrospective (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    root_cause_note_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    what_happened TEXT NULL,
    impact_summary TEXT NULL,
    response_summary TEXT NULL,
    lessons_learned TEXT NULL,
    prevention_plan TEXT NULL,
    action_items TEXT NULL,
    owner_id BIGINT NULL,
    due_at DATETIME NULL,
    regression_risk VARCHAR(32) NOT NULL DEFAULT 'LOW',
    repeated_incident TINYINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    published_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_retrospective_project_time(project_id, create_time),
    KEY idx_retrospective_incident(incident_id),
    KEY idx_retrospective_status(status),
    KEY idx_retrospective_owner(owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件事后回顾报告表';

CREATE TABLE tool_knowledge_quality_review (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    knowledge_document_id BIGINT NULL,
    retrospective_id BIGINT NULL,
    completeness_score TINYINT NOT NULL DEFAULT 0,
    accuracy_score TINYINT NOT NULL DEFAULT 0,
    actionability_score TINYINT NOT NULL DEFAULT 0,
    relevance_score TINYINT NOT NULL DEFAULT 0,
    review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    overall_status VARCHAR(32) NOT NULL DEFAULT 'NEEDS_WORK',
    checklist_json TEXT NULL,
    review_comment TEXT NULL,
    reviewer_id BIGINT NULL,
    reviewed_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_quality_review_project_time(project_id, create_time),
    KEY idx_quality_review_incident(incident_id),
    KEY idx_quality_review_status(review_status),
    KEY idx_quality_review_overall(overall_status),
    KEY idx_quality_review_reviewer(reviewer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识质量审查表';
