CREATE TABLE beta_trial_session (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    participant_role VARCHAR(64) NOT NULL,
    environment_type VARCHAR(32) NOT NULL,
    provider_mode VARCHAR(32) NOT NULL,
    github_oauth_status VARCHAR(32) NOT NULL,
    session_status VARCHAR(32) NOT NULL DEFAULT 'PLANNED',
    started_at DATETIME NULL,
    ended_at DATETIME NULL,
    completed_path_json JSON NULL,
    blocked_at_step VARCHAR(128) NULL,
    blocker_summary TEXT NULL,
    satisfaction_score INT NULL,
    continue_intent VARCHAR(32) NULL,
    summary TEXT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_beta_trial_project_time(project_id, create_time),
    KEY idx_beta_trial_status(session_status),
    KEY idx_beta_trial_env(environment_type, provider_mode),
    KEY idx_beta_trial_github(github_oauth_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Beta 试用会话表';

CREATE TABLE beta_trial_feedback (
    id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    category VARCHAR(64) NOT NULL,
    subcategory VARCHAR(64) NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'P2',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    title VARCHAR(255) NOT NULL,
    detail TEXT NULL,
    expected_behavior TEXT NULL,
    actual_behavior TEXT NULL,
    suggested_action TEXT NULL,
    triage_status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    mapped_incident_id BIGINT NULL,
    mapped_known_issue_id BIGINT NULL,
    release_blocking TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_beta_feedback_session(session_id),
    KEY idx_beta_feedback_project(project_id),
    KEY idx_beta_feedback_category(category, severity),
    KEY idx_beta_feedback_triage(triage_status, release_blocking)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Beta 试用反馈表';

CREATE TABLE beta_environment_readiness (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NULL,
    session_id BIGINT NULL,
    target_name VARCHAR(128) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    check_status VARCHAR(32) NOT NULL,
    summary TEXT NULL,
    detail_json JSON NULL,
    checked_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_beta_readiness_project(project_id),
    KEY idx_beta_readiness_session(session_id),
    KEY idx_beta_readiness_target(target_type, check_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Beta 环境就绪检查表';
