CREATE TABLE IF NOT EXISTS release_rollback_drill (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    release_label VARCHAR(128) NOT NULL,
    drill_status VARCHAR(32) NOT NULL,
    drill_scope VARCHAR(64) NOT NULL,
    environment_name VARCHAR(64) NOT NULL,
    owner_id BIGINT NULL,
    executor_id BIGINT NULL,
    planned_at DATETIME NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    duration_seconds BIGINT NULL,
    success_criteria TEXT NULL,
    rollback_steps_summary TEXT NULL,
    blockers_summary TEXT NULL,
    result_summary TEXT NULL,
    evidence_json JSON NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_release_rollback_drill_plan (plan_id),
    KEY idx_release_rollback_drill_project (project_id, create_time),
    KEY idx_release_rollback_drill_status (drill_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS release_audit_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    project_id BIGINT NULL,
    plan_id BIGINT NULL,
    release_label VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    actor_id BIGINT NULL,
    actor_name VARCHAR(128) NULL,
    summary VARCHAR(255) NOT NULL,
    detail TEXT NULL,
    related_step_id BIGINT NULL,
    related_verification_id BIGINT NULL,
    related_incident_id BIGINT NULL,
    related_alert_id BIGINT NULL,
    evidence_json JSON NULL,
    event_time DATETIME NOT NULL,
    create_time DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_release_audit_event_plan (plan_id, event_time),
    KEY idx_release_audit_event_project (project_id, event_time),
    KEY idx_release_audit_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS release_postmortem_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    release_label VARCHAR(128) NOT NULL,
    review_status VARCHAR(32) NOT NULL,
    overall_outcome VARCHAR(32) NOT NULL,
    summary TEXT NULL,
    what_went_well TEXT NULL,
    what_went_wrong TEXT NULL,
    customer_impact TEXT NULL,
    follow_up_actions TEXT NULL,
    reviewer_id BIGINT NULL,
    reviewed_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_release_postmortem_plan (plan_id),
    KEY idx_release_postmortem_project (project_id, create_time),
    KEY idx_release_postmortem_status (review_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
