CREATE TABLE IF NOT EXISTS governance_recommendation_item (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    source_snapshot_date DATE NOT NULL,
    policy_key VARCHAR(64) NOT NULL,
    guardrail_key VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    workflow_status VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    owner_id BIGINT NULL,
    owner_name VARCHAR(128) NULL,
    due_at DATETIME NULL,
    resolved_at DATETIME NULL,
    resolution_note TEXT NULL,
    source_evidence_json JSON NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_governance_recommendation_project(project_id, workflow_status),
    KEY idx_governance_recommendation_priority(priority, workflow_status),
    KEY idx_governance_recommendation_due(due_at, workflow_status),
    UNIQUE KEY uk_governance_recommendation_source(project_id, source_snapshot_date, policy_key, guardrail_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Governance recommendation item';

CREATE TABLE IF NOT EXISTS governance_waiver_request (
    id BIGINT PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    waiver_status VARCHAR(32) NOT NULL,
    waiver_scope VARCHAR(64) NOT NULL,
    requested_by BIGINT NULL,
    requested_by_name VARCHAR(128) NULL,
    approved_by BIGINT NULL,
    approved_by_name VARCHAR(128) NULL,
    reason_text TEXT NOT NULL,
    approval_note TEXT NULL,
    expires_at DATETIME NULL,
    revoked_at DATETIME NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    KEY idx_governance_waiver_project(project_id, waiver_status),
    KEY idx_governance_waiver_recommendation(recommendation_id),
    KEY idx_governance_waiver_expiry(expires_at, waiver_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Governance waiver request';

CREATE TABLE IF NOT EXISTS governance_workflow_snapshot (
    id BIGINT PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    total_recommendation_count INT NOT NULL DEFAULT 0,
    open_recommendation_count INT NOT NULL DEFAULT 0,
    in_progress_count INT NOT NULL DEFAULT 0,
    completed_count INT NOT NULL DEFAULT 0,
    blocked_count INT NOT NULL DEFAULT 0,
    overdue_count INT NOT NULL DEFAULT 0,
    active_waiver_count INT NOT NULL DEFAULT 0,
    expired_waiver_count INT NOT NULL DEFAULT 0,
    completion_rate DECIMAL(8,2) NOT NULL DEFAULT 0,
    overdue_rate DECIMAL(8,2) NOT NULL DEFAULT 0,
    summary_text VARCHAR(255) NOT NULL,
    create_time DATETIME NOT NULL,
    KEY idx_governance_workflow_snapshot_date(snapshot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Governance workflow snapshot';
