package com.aicoding.platform.orchestration.domain;

public enum ToolName {
    PROJECT_CONTEXT_SCAN,
    TASK_REQUIREMENT_ANALYSIS,
    MOCK_FILE_INSPECTION,
    MOCK_TEST_PLAN_SCAN,
    MOCK_SECURITY_REVIEW,
    MOCK_PATCH_PROPOSAL,
    READ_REPOSITORY_TREE,
    READ_FILE_SNIPPET,
    READ_DIFF_SUMMARY,
    READ_BRANCH_INFO,
    READ_CODE_INDEX,
    SEARCH_CODE_SYMBOL,
    SEARCH_CODE_CHUNK
}
