package com.aicoding.platform.github.domain;

public enum GithubErrorCode {
    OAUTH_NOT_CONFIGURED,
    OAUTH_STATE_INVALID,
    OAUTH_STATE_EXPIRED,
    OAUTH_TOKEN_EXCHANGE_FAILED,
    GITHUB_TOKEN_MISSING,
    GITHUB_AUTH_FAILED,
    GITHUB_RATE_LIMITED,
    GITHUB_REPO_NOT_FOUND,
    GITHUB_PR_NOT_FOUND,
    GITHUB_API_ERROR,
    GITHUB_BAD_RESPONSE,
    GITHUB_BINDING_NOT_FOUND
}
